Added controllers and views and changed startup based on the scaffolded new project with authorization.
TODO: error:
System.InvalidOperationException: 'The entity type 'IdentityUserLogin<string>' requires a primary key to be defined.'